title: Chunbo LIN's Homepage
page-top-title: Chunbo LIN
top-section-bg-text: Micro/Nano Optoelectronics
home-subtitle: Chunbo LIN&ensp;|&ensp;林春博
copyright-text: '&copy; Chunbo LIN 2021-2025. All Rights Reserved.'
